name: Simple CI

on: [push]  # Run workflow on push events

jobs:
  build:
    runs-on: self-hosted  # Use GitHub-hosted Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checkout code from repo

      - name: Run Script
        run: bash script.sh  # Execute the script
